spring.application.name=paymentprocessing
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.url=jdbc:mysql://localhost:3306/paymentdb?useSSL=false&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=n3u3da!
spring.jpa.hibernate.ddl-auto=update

# Email / OTP
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=rachitgoyal37@gmail.com
spring.mail.password=mgzgvsqykwadakrg
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true
app.otp.expiry-minutes=5
app.otp.recipient-email=rachitgoyal37@gmail.com