name: Payment Processing CI

on:
  push:
    branches:
      - main
      - feature/**

  pull_request:
    branches:
      - main


jobs:

  backend:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout Repository
        uses: actions/checkout@v4


      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21


      - name: Give execute permission
        run: chmod +x mvnw


      - name: Run Backend Tests
        run: ./mvnw clean test



  frontend:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout Repository
        uses: actions/checkout@v4


      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20


      - name: Install Dependencies
        working-directory: client
        run: npm install


      - name: Build React Application
        working-directory: client
        run: npm run build